version: '3'
services:
  web:
    image: node:9.11.1-alpine
    container_name: webapp-server
    user: root
    working_dir: /webapp
    environment:
      - NODE_ENV=development
    volumes:
      - .:/webapp
      - /webapp/node_modules
    ports:
      - 8080:9000
    command:
      - /bin/sh
      - -c
      - |
        npm i
        npm run start
    restart: always
    # (默认只读)有写的权限
    privileged: true 
    networks:
      - webapp-networks
networks:
   webapp-networks:
     driver: bridge

# docker-compose up -d
# docker-compose ps
# docker-compose start/stop/restart
# docker-compose down
